/* PRhehydrate — Korean strings for tables.html, keyed by the English text in js/tables.js. */
window.RH_TABLES_KR = {
 "Clinical Reference Tables": "임상 참고 표",
 "Reference tables for dehydration assessment and rehydration, led by WHO guidance, including severe acute malnutrition (SAM). Every table links to its source. For use alongside the PRhehydrate calculator.": "탈수 평가와 수액 보충을 위한 참고 표로, WHO 지침을 중심으로 중증 급성 영양실조(SAM)를 포함합니다. 모든 표에 출처 링크가 있습니다. PRhehydrate 계산기와 함께 사용하십시오.",
 "Back to calculator": "계산기로 돌아가기",
 "Source": "출처",
 "Sources": "출처",
 "For clinical reference only. Verify all values against current authoritative sources before use. PRhehydrate is not a substitute for clinical judgment.": "임상 참고용입니다. 사용 전 모든 값을 최신 공식 자료와 대조해 확인하십시오. PRhehydrate는 임상적 판단을 대신하지 않습니다.",
 "Tables are available in English and French.": "표는 영어, 프랑스어, 한국어로 제공됩니다.",
 "Source code": "소스 코드",
 "This is the code running in your browser now, printed from the loaded file.": "지금 브라우저에서 실행 중인 코드이며, 불러온 파일에서 그대로 표시합니다.",
 "WHO: Assessing dehydration": "WHO: 탈수 평가",
 "Children with diarrhoea — columns A, B, C": "설사 소아 — A, B, C 열",
 "Sign": "징후",
 "A — No dehydration": "A — 탈수 없음",
 "B — Some dehydration": "B — 경도–중등도 탈수",
 "C — Severe dehydration": "C — 중증 탈수",
 "Condition¹": "전신 상태¹",
 "Well, alert": "양호, 명료",
 "Restless, irritable": "보챔, 과민",
 "Lethargic or unconscious": "기면 또는 의식 없음",
 "Eyes²": "눈²",
 "Normal": "정상",
 "Sunken": "꺼짐",
 "Thirst": "갈증",
 "Drinks normally, not thirsty": "정상적으로 마심, 갈증 없음",
 "Thirsty, drinks eagerly": "갈증, 허겁지겁 마심",
 "Drinks poorly or not able to drink": "잘 못 마시거나 마시지 못함",
 "Skin pinch³": "피부 꼬집기³",
 "Goes back quickly": "빨리 돌아옴",
 "Goes back slowly": "천천히 돌아옴",
 "Goes back very slowly (≥ 2 s)": "매우 천천히 돌아옴 (≥ 2초)",
 "Decide": "판정",
 "Not enough signs for B or C": "B 또는 C에 해당하는 징후 부족",
 "Two or more signs in B": "B에 2개 이상",
 "Two or more signs in C": "C에 2개 이상",
 "Treat": "치료",
 "Plan A": "Plan A",
 "Weigh; Plan B": "체중 측정; Plan B",
 "Weigh; Plan C urgently": "체중 측정; 즉시 Plan C",
 "¹ Lethargic is not the same as asleep: the child's mental state is dull and the child cannot be fully awakened.": "¹ 기면은 잠든 것과 다릅니다: 정신 상태가 둔하고 완전히 깨울 수 없습니다.",
 "² In some children the eyes are normally somewhat sunken — ask the mother whether they look different than usual.": "² 일부 소아는 원래 눈이 약간 꺼져 보입니다 — 평소와 다른지 어머니에게 물어보십시오.",
 "³ The skin pinch is less useful in marasmus, kwashiorkor or obese children — see the SAM tables below.": "³ 피부 꼬집기는 소모형 영양실조, 콰시오커, 비만 소아에서 유용성이 낮습니다 — 아래 SAM 표를 참고하십시오.",
 "WHO: Treatment plans A, B and C": "WHO: 치료 계획 A, B, C",
 "Volumes and timing": "용량과 시간",
 "Plan": "계획",
 "What to give": "투여 내용",
 "A — no dehydration": "A — 탈수 없음",
 "Extra fluid after each loose stool: < 2 years 50–100 mL; ≥ 2 years 100–200 mL. Zinc 10–14 days: ≤ 6 months 10 mg/day, ≥ 6 months 20 mg/day. Continue feeding.": "묽은 변 1회마다 추가 수분: 2세 미만 50–100 mL; 2세 이상 100–200 mL. 아연 10–14일: 6개월 이하 10 mg/일, 6개월 이상 20 mg/일. 수유·식사를 계속.",
 "B — some dehydration": "B — 경도–중등도 탈수",
 "ORS 75 mL/kg over 4 h (give more if the child wants more). Reassess at 4 h.": "ORS 75 mL/kg를 4시간 동안 (더 원하면 더 줌). 4시간에 재평가.",
 "C — severe dehydration": "C — 중증 탈수",
 "IV Ringer's lactate (or normal saline) 100 mL/kg: 30 mL/kg then 70 mL/kg. Infants < 12 months: 1 h + 5 h. Older: 30 min + 2.5 h. Repeat the first portion if the radial pulse is still very weak. ORS ~5 mL/kg/h as soon as the child can drink.": "정맥 링거젖산액(또는 생리식염수) 100 mL/kg: 30 mL/kg 후 70 mL/kg. 12개월 미만 영아: 1시간 + 5시간. 그 이상: 30분 + 2.5시간. 요골 맥박이 여전히 매우 약하면 첫 분량 반복. 마실 수 있게 되면 곧바로 ORS 약 5 mL/kg/h.",
 "Plan B — approximate ORS in the first 4 hours (use age only if weight is unknown; otherwise weight × 75)": "Plan B — 처음 4시간의 대략적 ORS 양 (체중을 모를 때만 나이 사용; 아니면 체중 × 75)",
 "Age": "나이",
 "Weight": "체중",
 "< 4 months": "< 4개월",
 "4–11 months": "4–11개월",
 "12–23 months": "12–23개월",
 "2–4 years": "2–4세",
 "5–14 years": "5–14세",
 "≥ 15 years": "≥ 15세",
 "Not for children with severe acute malnutrition — see the SAM protocols below.": "중증 급성 영양실조 소아에는 해당하지 않습니다 — 아래 SAM 프로토콜을 참고하십시오.",
 "Severity of dehydration": "탈수의 중증도",
 "Signs & symptoms by category": "범주별 징후와 증상",
 "Sign / Symptom": "징후 / 증상",
 "Minimal or No Dehydration": "탈수 경미 또는 없음",
 "<3% body weight loss; 3%–5% fluid deficit": "체중 감소 <3%; 수분 결핍 3%–5%",
 "Mild to Moderate Dehydration": "경도–중등도 탈수",
 "3%–9% body weight loss; 6%–9% fluid deficit": "체중 감소 3%–9%; 수분 결핍 6%–9%",
 "Severe Dehydration": "중증 탈수",
 ">9% body weight loss; >10% fluid deficit": "체중 감소 >9%; 수분 결핍 >10%",
 "Mental status": "정신 상태",
 "Well; alert": "양호; 명료",
 "Normal, fatigued, or restless, irritable": "정상, 피곤, 또는 보챔, 과민",
 "Apathetic, lethargic, unconscious": "무관심, 기면, 의식 없음",
 "Drinks normally; might refuse liquids": "정상적으로 마심; 음료를 거부할 수 있음",
 "Thirsty; eager to drink": "갈증; 열심히 마심",
 "Drinks poorly; unable to drink": "잘 못 마심; 마시지 못함",
 "Heart rate": "심박수",
 "Normal to increased": "정상에서 증가",
 "Tachycardia, with bradycardia in severe cases": "빈맥, 중증에서는 서맥",
 "Quality of pulses": "맥박의 질",
 "Normal to decreased": "정상에서 감소",
 "Weak, thready, or impalpable": "약함, 가늘거나 촉지 안 됨",
 "Breathing": "호흡",
 "Normal; fast": "정상; 빠름",
 "Deep": "깊음",
 "Eyes": "눈",
 "Slightly sunken": "약간 꺼짐",
 "Deeply sunken": "깊이 꺼짐",
 "Tears": "눈물",
 "Present": "있음",
 "Decreased": "감소",
 "Absent": "없음",
 "Mouth and tongue": "입과 혀",
 "Moist": "촉촉함",
 "Dry": "건조",
 "Parched": "바싹 마름",
 "Skin fold": "피부 주름",
 "Instant recoil": "즉시 돌아옴",
 "Recoil in <2 s": "<2초에 돌아옴",
 "Recoil in >2 s": ">2초에 돌아옴",
 "Capillary refill": "모세혈관 재충혈",
 "Normal (<3 s)": "정상 (<3초)",
 "Prolonged": "지연",
 "Prolonged; minimal": "지연; 최소",
 "Extremities": "사지",
 "Warm": "따뜻함",
 "Cool": "서늘함",
 "Cold; mottled; cyanotic": "차가움; 얼룩덜룩; 청색증",
 "Urine output": "소변량",
 "Minimal": "최소",
 "US framework (CDC/AAP). WHO settings use the A/B/C table above.": "미국 기준(CDC/AAP). WHO 환경에서는 위의 A/B/C 표를 사용하십시오.",
 "Clinical Dehydration Scale (Goldman)": "임상 탈수 척도 (Goldman)",
 "Scoring criteria and interpretation": "채점 기준과 해석",
 "Characteristic": "항목",
 "General appearance": "전반적 외관",
 "Thirsty, restless, or lethargic but irritable when touched": "갈증, 보챔, 또는 기면이지만 만지면 과민",
 "Drowsy, limp, cold or sweaty ± comatose": "졸림, 늘어짐, 차갑거나 땀 흘림 ± 혼수",
 "Extremely sunken": "매우 꺼짐",
 "Mucus membrane": "점막",
 "Sticky": "끈적함",
 "Total Score": "총점",
 "Interpretation": "해석",
 "No dehydration": "탈수 없음",
 "Some dehydration": "경도 탈수",
 "Moderate to severe dehydration": "중등도–중증 탈수",
 "Severe acute malnutrition: who has it?": "중증 급성 영양실조: 해당 기준",
 "Children 6–59 months": "6–59개월 소아",
 "Criterion": "기준",
 "Severe (SAM)": "중증 (SAM)",
 "Moderate wasting": "중등도 소모증",
 "MUAC": "상완위둘레 (MUAC)",
 "Weight-for-height / length z-score": "신장(신장·신장길이)별 체중 z점수",
 "Bilateral pitting (nutritional) oedema": "양측 함요(영양성) 부종",
 "Any grade (+, ++, +++) = SAM": "모든 등급(+, ++, +++) = SAM",
 "Rehydration": "수액 보충",
 "SAM protocol (ReSoMal preferred; low-osmolarity ORS if unavailable)": "SAM 프로토콜 (ReSoMal 우선; 없으면 저삼투압 ORS)",
 "Standard WHO plans with low-osmolarity ORS": "저삼투압 ORS를 사용하는 WHO 표준 계획",
 "Under 6 months: MUAC is not used for SAM; use weight-for-length < −3 SD or oedema. Admit for inpatient care if any IMCI danger sign, acute medical problem, oedema +++, or failed appetite test.": "6개월 미만: SAM 판정에 상완위둘레를 쓰지 않습니다; 신장길이별 체중 < −3 SD 또는 부종을 사용합니다. IMCI 위험 징후, 급성 내과 문제, 부종 +++, 식욕 검사 실패 중 하나라도 있으면 입원 치료.",
 "Dehydration signs in SAM": "SAM에서의 탈수 징후",
 "MSF table adapted for SAM — 2 or more signs": "SAM용으로 수정한 MSF 표 — 2개 이상",
 "Severe dehydration": "중증 탈수",
 "No thirst, drinks normally": "갈증 없음, 정상적으로 마심",
 "Unable to drink or drinks poorly": "마시지 못하거나 잘 못 마심",
 "Reduced": "감소",
 "Absent for several hours": "수 시간째 없음",
 "Recent frequent watery diarrhoea and/or vomiting": "최근 잦은 수양성 설사 및/또는 구토",
 "Yes": "예",
 "Recent obvious rapid weight loss": "최근 뚜렷하고 빠른 체중 감소",
 "No": "아니오",
 "Sunken eyes and a slow skin pinch are often present in SAM without dehydration; oedema can mask dehydration (WHO 2023 B6; MSF 2024).": "SAM에서는 탈수 없이도 눈 꺼짐과 느린 피부 꼬집기가 흔하며, 부종이 탈수를 가릴 수 있습니다 (WHO 2023 B6; MSF 2024).",
 "WHO 2013: dehydration is over-diagnosed in SAM — assume all children with watery diarrhoea or reduced urine output have some dehydration; IV only for shock.": "WHO 2013: SAM에서 탈수는 과다 진단됩니다 — 수양성 설사나 소변량 감소가 있으면 모두 경도–중등도 탈수로 가정하고, 정맥 수액은 쇼크에만 사용합니다.",
 "ACF 2011: diagnose from the history (recent watery diarrhoea, carer reports the eyes recently sank, no full veins, no oedema); children with oedema cannot be 'dehydrated'.": "ACF 2011: 병력으로 진단합니다(최근 수양성 설사, 보호자가 눈이 최근 꺼졌다고 함, 정맥 충만 없음, 부종 없음); 부종이 있는 소아는 '탈수'일 수 없습니다.",
 "SAM rehydration protocols compared": "SAM 수액 프로토콜 비교",
 "The five protocols selectable in Settings": "설정에서 선택할 수 있는 5개 프로토콜",
 "WHO 2013/2023 (default)": "WHO 2013/2023 (기본값)",
 "India 2011": "인도 2011",
 "Oral fluid": "경구 수액",
 "Reduced-osmolarity ORS + 15 mL KCl/L": "저삼투압 ORS + KCl 15 mL/L",
 "Some dehydration (oral/NG)": "경도–중등도 탈수 (경구/비위관)",
 "5 mL/kg every 30 min × 2 h, then 5–10 mL/kg/h for 4–10 h alternating with F-75; max 12 h": "2시간 동안 30분마다 5 mL/kg, 이후 4–10시간 동안 5–10 mL/kg/h를 F-75와 교대; 최대 12시간",
 "20 mL/kg/h × 2 h, then 10 mL/kg/h to target weight (current × 1.06)": "20 mL/kg/h × 2시간, 이후 목표 체중(현재 × 1.06)까지 10 mL/kg/h",
 "10 mL/kg/h × 2 h, then adjust by hourly weight; stop at target (≤ +5%)": "10 mL/kg/h × 2시간, 이후 매시간 체중으로 조절; 목표(≤ +5%)에서 중단",
 "5 mL/kg every 30 min × 2 h, then 5–10 mL/kg alternate hours up to 10 h": "2시간 동안 30분마다 5 mL/kg, 이후 최대 10시간 동안 한 시간 걸러 5–10 mL/kg",
 "10 mL/kg/h × 2 h, then 7.5 mL/kg/h alternating with F-75 for 10 h (5–10)": "10 mL/kg/h × 2시간, 이후 10시간 동안 7.5 mL/kg/h를 F-75와 교대 (5–10)",
 "Severe, no shock": "중증, 쇼크 없음",
 "Same oral regimen; IV (Chart 8) only if oral/NG impossible": "같은 경구 요법; 경구/비위관 불가 시에만 정맥(Chart 8)",
 "ReSoMal 20 mL/kg over 1 h (target × 1.1); if vomiting G5%-RL 10 mL/kg/h × 2 h": "ReSoMal 20 mL/kg를 1시간 동안 (목표 × 1.1); 구토 시 G5%-RL 10 mL/kg/h × 2시간",
 "Same oral regimen": "같은 경구 요법",
 "Shock: IV": "쇼크: 정맥",
 "15 mL/kg over 1 h (RL-5% glucose, ½-Darrow's-5% glucose, or 0.45% NaCl-5% glucose); repeat once if improving, then ReSoMal 10 mL/kg/h": "15 mL/kg를 1시간 동안 (RL-5% 포도당, ½ 다로우-5% 포도당, 또는 0.45% NaCl-5% 포도당); 호전되면 1회 반복 후 ReSoMal 10 mL/kg/h",
 "Ceftriaxone 80 mg/kg; G5%-RL 10 mL/kg/h × 2 h; reassess at 1 h and 2 h": "세프트리악손 80 mg/kg; G5%-RL 10 mL/kg/h × 2시간; 1시간과 2시간에 재평가",
 "15 mL/kg over 1 h (half-strength fluids); repeat while weight is not rising": "15 mL/kg를 1시간 동안 (반농도 수액); 체중이 늘지 않는 동안 반복",
 "10% glucose 5 mL/kg; 15 mL/kg over 1 h; repeat once if improving, then ORS 10 mL/kg/h": "10% 포도당 5 mL/kg; 15 mL/kg를 1시간 동안; 호전되면 1회 반복 후 ORS 10 mL/kg/h",
 "RL-5% dextrose 20 mL/kg over 2 h": "RL-5% 포도당 20 mL/kg를 2시간 동안",
 "No response": "반응 없음",
 "After 2 boluses: IV 4 mL/kg/h, whole blood 10 mL/kg over 3 h": "볼루스 2회 후: 정맥 4 mL/kg/h, 전혈 10 mL/kg를 3시간 동안",
 "Continue 10 mL/kg/h; check Hb and transfuse": "10 mL/kg/h 지속; Hb 확인 후 수혈",
 "Weight up but no better: toxic/septic/cardiogenic shock — stop": "체중은 늘었으나 호전 없음: 독성/패혈성/심인성 쇼크 — 중단",
 "Septic shock: IV 4 mL/kg/h, review antibiotics, dopamine": "패혈성 쇼크: 정맥 4 mL/kg/h, 항생제 재검토, 도파민",
 "Severe anaemia: transfuse instead of Ringer's": "중증 빈혈: 링거 대신 수혈",
 "Stop / overload": "중단 / 과부하",
 "Oral: RR +5 and pulse +25. IV: RR +5 and pulse +15, liver ↑, crackles, JVP ↑, gallop": "경구: 호흡수 +5 및 맥박 +25. 정맥: 호흡수 +5 및 맥박 +15, 간 ↑, 수포음, 경정맥압 ↑, 분마음",
 "RR ≥ +10 or HR ≥ +20 plus SpO₂ ↓ > 5%, crackles, gallop, liver ↑ or new oedema": "호흡수 ≥ +10 또는 심박수 ≥ +20에 더해 SpO₂ ↓ > 5%, 수포음, 분마음, 간 ↑ 또는 새 부종",
 "Target weight, full veins, oedema, liver +1 cm, RR +5, grunting, crackles, gallop": "목표 체중, 정맥 충만, 부종, 간 +1 cm, 호흡수 +5, 그렁거림, 수포음, 분마음",
 "RR +5 and pulse +15, jugular veins engorged, puffy eyelids": "호흡수 +5 및 맥박 +15, 경정맥 충만, 눈꺼풀 부종",
 "—": "—",
 "Per watery stool": "수양성 변 1회당",
 "5 mL/kg (ORS outpatient; ReSoMal inpatient)": "5 mL/kg (외래 ORS; 입원 ReSoMal)",
 "30 mL (6–24 months only)": "30 mL (6–24개월만)",
 "< 2 y ~50 mL; ≥ 2 y 100 mL ORS": "2세 미만 약 50 mL; 2세 이상 100 mL ORS",
 "Not specified": "명시되지 않음",
 "Cholera or profuse watery diarrhoea: standard ORS, not ReSoMal. MSF (SAM + cholera): some dehydration 75 mL/kg ORS over 4 h; severe/shock RL 20 mL/kg over 30 min (up to 3 boluses) then 70 mL/kg over 6 h — same volume as non-malnourished children, twice as slowly.": "콜레라 또는 다량의 수양성 설사: ReSoMal이 아닌 표준 ORS. MSF (SAM + 콜레라): 경도–중등도 탈수 ORS 75 mL/kg를 4시간 동안; 중증/쇼크 RL 20 mL/kg를 30분 동안(볼루스 최대 3회) 후 70 mL/kg를 6시간 동안 — 영양실조가 없는 소아와 같은 양을 두 배 천천히.",
 "Earlier WHO guidance (Treatment of diarrhoea 2005, §8.2) gave 70–100 mL/kg over 12 h, starting at ~10 mL/kg/h; the 2013 Pocket Book regimen above supersedes it.": "이전 WHO 지침(설사 치료 2005, §8.2)은 12시간 동안 70–100 mL/kg, 약 10 mL/kg/h로 시작하도록 했으나, 위의 2013 포켓북 요법이 이를 대체합니다.",
 "GASTROSAM (2026): in 415 children with SAM and moderate/severe dehydration, standard WHO ORS gave outcomes similar to ReSoMal, with no fluid overload in either arm.": "GASTROSAM (2026): 중등도/중증 탈수를 동반한 SAM 소아 415명에서 표준 WHO ORS는 ReSoMal과 비슷한 결과를 보였고, 두 군 모두 수분 과부하가 없었습니다.",
 "ORS Comparison": "ORS 비교",
 "Composition of common oral rehydration solutions": "일반적인 경구 수액제의 조성",
 "ORS Product": "ORS 제품",
 "Carbs (g/L)": "탄수화물 (g/L)",
 "Osmolarity (mOsm/L)": "삼투압 (mOsm/L)",
 "WHO low-osmolarity (2002)": "WHO 저삼투압 (2002)",
 "ᵃ WHO ORS contains trisodium citrate 10 mmol/L (2.9 g/L), which supplies about 30 mEq/L of base.": "ᵃ WHO ORS는 구연산삼나트륨 10 mmol/L (2.9 g/L)를 포함하며, 이는 약 30 mEq/L의 염기를 공급합니다.",
 "WHO low-osmolarity ORS is the formulation in WHO/UNICEF sachets (one sachet per litre of clean water). Check which brands your pharmacy stocks and that they match this composition.": "WHO 저삼투압 ORS는 WHO/UNICEF 사셰의 조성입니다(깨끗한 물 1리터에 사셰 1개). 약제부에 있는 제품과 조성이 일치하는지 확인하십시오.",
 "The ESPGHAN option (Na⁺ 60 mEq/L, ~200–250 mOsm/L) can be selected under Institution settings.": "ESPGHAN 옵션(Na⁺ 60 mEq/L, 약 200–250 mOsm/L)은 기관 설정에서 선택할 수 있습니다.",
 "Commercial products: manufacturer labels.": "시판 제품: 제조사 표시.",
 "ReSoMal and other SAM solutions": "ReSoMal 및 기타 SAM용 수액",
 "Composition per litre": "1리터당 조성",
 "Solution": "수액",
 "Citrate": "구연산",
 "Sugars": "당류",
 "Osmolarity": "삼투압",
 "mmol/L unless stated": "별도 표시가 없으면 mmol/L",
 "ReSoMal, commercial sachet (84 g in 2 L)": "ReSoMal, 시판 사셰 (84 g을 2 L에)",
 "glucose 55, sucrose 73": "포도당 55, 자당 73",
 "ReSoMal, WHO recipe from WHO-ORS (2013)": "ReSoMal, WHO-ORS로 만드는 WHO 조제법 (2013)",
 "+ 50 g sucrose per 2 L": "2 L당 자당 50 g 추가",
 "Modified ORS for SAM (WHO 2005)": "SAM용 변형 ORS (WHO 2005)",
 "+ 25 g/L sugar": "당 25 g/L 추가",
 "India MoHFW: reduced-osmolarity ORS + 15 mL KCl per litre": "인도 MoHFW: 저삼투압 ORS + 1리터당 KCl 15 mL",
 "20 + 20": "20 + 20",
 "glucose 75": "포도당 75",
 "ReSoMal only under medical supervision in a health facility; not for cholera or for uncomplicated malnutrition (use standard ORS). Commercial ReSoMal and ORS are preferred to solutions prepared in the facility or at home.": "ReSoMal은 의료기관에서 의료진 감독하에만 사용; 콜레라나 합병증 없는 영양실조에는 사용하지 않음(표준 ORS 사용). 기관이나 가정에서 만든 수액보다 시판 ReSoMal과 ORS가 선호됩니다.",
 "“—” = not stated in the source.": "“—” = 출처에 명시되지 않음.",
 "Preparing solutions": "수액 조제",
 "Recipes as given in the sources": "출처에 제시된 조제법",
 "Recipe": "조제법",
 "Notes": "비고",
 "Home-made salt–sugar solution": "가정용 소금–설탕 용액",
 "3 g/L table salt (one level teaspoon) + 18 g/L sugar (sucrose)": "식염 3 g/L (평평하게 1 티스푼) + 설탕(자당) 18 g/L",
 "WHO: effective, but not generally recommended — the recipe is often forgotten, ingredients may be unavailable, or too little is given. Prefer ORS; salted home fluids (rice water, soup) are alternatives.": "WHO: 효과는 있으나 일반적으로 권장하지 않음 — 조제법을 자주 잊고, 재료가 없거나, 너무 적게 주기 쉽습니다. ORS를 우선하고, 소금을 넣은 가정 음료(쌀뜨물, 수프)를 대안으로 씁니다.",
 "ReSoMal from WHO-ORS": "WHO-ORS로 만드는 ReSoMal",
 "2 L water + one 1-litre packet WHO-ORS + 50 g sucrose + 40 mL electrolyte/mineral solution (or 45 mL of 10% KCl: 100 g KCl in 1 L)": "물 2 L + WHO-ORS 1리터용 1포 + 자당 50 g + 전해질/미네랄 용액 40 mL (또는 10% KCl 45 mL: 1 L에 KCl 100 g)",
 "≈ 45 mmol Na, 40 mmol K, 3 mmol Mg per litre (WHO 2013). Not for cholera or profuse watery diarrhoea.": "1리터당 약 Na 45 mmol, K 40 mmol, Mg 3 mmol (WHO 2013). 콜레라나 다량의 수양성 설사에는 사용하지 않음.",
 "Ringer's lactate with 5% glucose (G5%-RL)": "5% 포도당 첨가 링거젖산액 (G5%-RL)",
 "Remove 50 mL from a 500 mL RL bag; add 50 mL of 50% glucose": "500 mL RL 백에서 50 mL를 빼고 50% 포도당 50 mL 추가",
 "MSF 2024; Kenya BPP 2022 (50 mL 50% dextrose + 450 mL RL).": "MSF 2024; 케냐 BPP 2022 (50% 포도당 50 mL + RL 450 mL).",
 "RL for cholera infusion (SAM)": "콜레라 주입용 RL (SAM)",
 "Add 100 mL of 50% glucose to each litre of RL": "RL 1리터마다 50% 포도당 100 mL 추가",
 "Formulas & code": "공식과 코드",
 "Every calculation the app performs": "앱이 수행하는 모든 계산",
 "Sports Drinks Comparison": "스포츠음료 비교",
 "Nutritional composition per serving (US products)": "1회 제공량당 영양 조성 (미국 제품)",
 "Brand": "상표",
 "Serving": "제공량",
 "Carbs (g)": "탄수화물 (g)",
 "% Carb": "탄수화물 %",
 "Sugars (g)": "당류 (g)",
 "Other Key Ingredients": "기타 주요 성분",
 "Electrolytes, natural flavor": "전해질, 천연 향료",
 "Vitamins C, B12, calcium, magnesium": "비타민 C, B12, 칼슘, 마그네슘",
 "Coconut water, vitamins B3, B5, B6, etc": "코코넛 워터, 비타민 B3, B5, B6 등",
 "Vitamins B6, C, E, niacin, pantothenic acid": "비타민 B6, C, E, 나이아신, 판토텐산",
 "Vitamins B, C, E": "비타민 B, C, E",
 "Magnesium, calcium": "마그네슘, 칼슘",
 "Vitamins B12, C, calcium, magnesium": "비타민 B12, C, 칼슘, 마그네슘",
 "Zinc, chloride 440 mg, zinc 2.8 mg": "아연, 염화물 440 mg, 아연 2.8 mg",
 "Vitamin C, calcium, magnesium": "비타민 C, 칼슘, 마그네슘",
 "Ca 47 mg, Mg 100 mg, Zn 1 mg, Cl 78 mg, Mn 0.2 mg, vitamin C 100 mg": "Ca 47 mg, Mg 100 mg, Zn 1 mg, Cl 78 mg, Mn 0.2 mg, 비타민 C 100 mg",
 "a BodyArmor Lyte — serving size (12 oz) from website; nutrition label did not specify which size.": "a BodyArmor Lyte — 제공량(12 oz)은 웹사이트 기준; 영양 표시에 크기가 명시되지 않음.",
 "b Nuun Sport — product supplied as a dissolvable tablet.": "b Nuun Sport — 녹여 먹는 정제 형태.",
 "c Skratch Labs Sport Hydration Mix — product supplied as a powder mixture.": "c Skratch Labs Sport Hydration Mix — 분말 혼합 형태.",
 "d Ultima Replenisher — composition reported per scoop.": "d Ultima Replenisher — 1스쿱 기준 조성.",
 "Sports drinks are not oral rehydration solutions; compare their sodium and sugar with the ORS table above.": "스포츠음료는 경구 수액제가 아닙니다; 나트륨과 당을 위 ORS 표와 비교해 보십시오.",
 "Manufacturer nutrition labels; data as published.": "제조사 영양 표시; 공개된 자료 그대로.",
 "Holliday–Segar: 100 mL/kg for the first 10 kg + 50 mL/kg for the next 10 kg + 20 mL/kg per kg above 20; hourly = daily ÷ 24.": "Holliday–Segar: 처음 10 kg 100 mL/kg + 다음 10 kg 50 mL/kg + 20 kg 초과분 kg당 20 mL/kg; 시간당 = 일일 ÷ 24.",
 "Deficit (mL) = deficit % × weight (kg) × 10 (1% of body weight ≈ 10 mL/kg).": "결핍량 (mL) = 결핍 % × 체중 (kg) × 10 (체중 1% ≈ 10 mL/kg).",
 "% dehydration = (well weight − current weight) ÷ well weight × 100, capped at 15%.": "탈수 % = (건강 시 체중 − 현재 체중) ÷ 건강 시 체중 × 100, 최대 15%.",
 "10 mL/kg per watery stool + 2 mL/kg per emesis.": "수양성 변 1회당 10 mL/kg + 구토 1회당 2 mL/kg.",
 "Goldman CDS: sum of 4 items (0–2 each); 0 none, 1–4 some, 5–8 moderate/severe.": "Goldman CDS: 4개 항목 합계(각 0–2); 0 없음, 1–4 경도, 5–8 중등도/중증.",
 "WHO: ≥ 2 signs in column C = severe; ≥ 2 signs in B or C = some; otherwise none.": "WHO: C열 징후 ≥ 2 = 중증; B 또는 C열 징후 ≥ 2 = 경도–중등도; 그 외 없음.",
 "ORS volume = rate (mL/kg, WHO 75) × weight, over the chosen hours.": "ORS 용량 = 용량(mL/kg, WHO 75) × 체중, 선택한 시간 동안.",
 "WHO Plan C: 100 mL/kg = 30 mL/kg then 70 mL/kg; < 12 months over 1 h + 5 h, older over 30 min + 2.5 h.": "WHO Plan C: 100 mL/kg = 30 mL/kg 후 70 mL/kg; 12개월 미만은 1시간 + 5시간, 그 이상은 30분 + 2.5시간.",
 "Bolus-first: 20 mL/kg boluses; phase 2 = (deficit − boluses given) + 12 h maintenance, over 12 h.": "볼루스 우선: 20 mL/kg 볼루스; 2단계 = (결핍량 − 투여한 볼루스) + 12시간 유지량, 12시간 동안.",
 "SAM if MUAC < 115 mm (6–59 months), weight-for-height < −3 SD, or bilateral pitting oedema.": "상완위둘레 < 115 mm (6–59개월), 신장별 체중 < −3 SD, 또는 양측 함요부종이면 SAM.",
 "SAM protocol: ": "SAM 프로토콜: "
};
