/* PRhehydrate — Chinese strings for tables.html, keyed by the English text in js/tables.js. */
window.RH_TABLES_ZH = {
 "Clinical Reference Tables": "临床参考表",
 "Back to calculator": "返回计算器",
 "Source": "来源",
 "Sources": "来源",
 "For clinical reference only. Verify all values against current authoritative sources before use. PRhehydrate is not a substitute for clinical judgment.": "仅供临床参考。使用前请对照最新权威资料核实所有数值。PRhehydrate不能替代临床判断。",
 "Source code": "源代码",
 "SAM protocol: ": "SAM方案：",
 "Theme and language": "主题和语言",
 "Color theme": "颜色主题",
 "Change language": "切换语言",
 "WHO: Assessing dehydration": "WHO：脱水评估",
 "Sign": "体征",
 "A: No dehydration": "A：无脱水",
 "B: Some dehydration": "B：部分脱水",
 "C: Severe dehydration": "C：重度脱水",
 "Condition¹": "一般状态¹",
 "Well, alert": "精神好，警觉",
 "Restless, irritable": "烦躁、易激惹",
 "Lethargic or unconscious": "嗜睡或意识不清",
 "Eyes²": "眼睛²",
 "Normal": "正常",
 "Sunken": "凹陷",
 "Thirst": "口渴",
 "Drinks normally, not thirsty": "饮水正常，无口渴",
 "Thirsty, drinks eagerly": "口渴，急于饮水",
 "Drinks poorly or not able to drink": "饮水差或不能饮水",
 "Skin pinch³": "皮肤弹性³",
 "Goes back quickly": "迅速回弹",
 "Goes back slowly": "回弹缓慢",
 "Goes back very slowly (≥ 2 s)": "回弹极慢（≥ 2 秒）",
 "Decide": "判定",
 "Not enough signs for B or C": "不足以归入B或C",
 "Two or more signs in B": "B栏中有两项及以上体征",
 "Two or more signs in C": "C栏中有两项及以上体征",
 "Treat": "处理",
 "Plan A": "方案A",
 "Weigh; Plan B": "称体重；方案B",
 "Weigh; Plan C urgently": "称体重；紧急实施方案C",
 "¹ Lethargic is not the same as asleep: the child's mental state is dull and the child cannot be fully awakened.": "¹ 嗜睡不同于睡眠：患儿神志迟钝，不能完全唤醒。",
 "² In some children the eyes are normally somewhat sunken. Ask the mother whether they look different than usual.": "² 部分患儿平时眼睛就略凹陷。应询问母亲是否与平时不同。",
 "³ The skin pinch is less useful in marasmus, kwashiorkor or obese children. See the SAM tables below.": "³ 消瘦型或水肿型（kwashiorkor）营养不良及肥胖患儿中，皮肤弹性检查参考价值较低。见下方SAM表。",
 "WHO: Treatment plans A, B and C": "WHO：治疗方案A、B、C",
 "Plan": "方案",
 "What to give": "给予内容",
 "A: no dehydration": "A：无脱水",
 "Extra fluid after each loose stool: < 2 years 50–100 mL; ≥ 2 years 100–200 mL. Zinc 10–14 days: ≤ 6 months 10 mg/day, ≥ 6 months 20 mg/day. Continue feeding.": "每次稀便后额外补液：< 2 岁 50–100 mL；≥ 2 岁 100–200 mL。补锌 10–14 天：≤ 6 月龄 10 mg/天，≥ 6 月龄 20 mg/天。继续喂养。",
 "B: some dehydration": "B：部分脱水",
 "ORS 75 mL/kg over 4 h (give more if the child wants more). Reassess at 4 h.": "ORS 75 mL/kg，4 小时内服完（患儿想喝可多给）。4 小时后重新评估。",
 "C: severe dehydration": "C：重度脱水",
 "IV Ringer's lactate (or normal saline) 100 mL/kg: 30 mL/kg then 70 mL/kg. Infants < 12 months: 1 h + 5 h. Older: 30 min + 2.5 h. Repeat the first portion if the radial pulse is still very weak. ORS ~5 mL/kg/h as soon as the child can drink.": "静脉输注乳酸林格液（或生理盐水）100 mL/kg：先 30 mL/kg，再 70 mL/kg。< 12 月龄婴儿：1 小时 + 5 小时。年长儿：30 分钟 + 2.5 小时。若桡动脉搏动仍很弱，重复第一部分。患儿能饮水后即给予 ORS 约 5 mL/kg/h。",
 "Plan B: approximate ORS in the first 4 hours (use age only if weight is unknown; otherwise weight × 75)": "方案B：前 4 小时 ORS 估算量（仅在体重未知时按年龄估算；否则为体重 × 75）",
 "Age": "年龄",
 "Weight": "体重",
 "< 4 months": "< 4 月龄",
 "4–11 months": "4–11 月龄",
 "12–23 months": "12–23 月龄",
 "2–4 years": "2–4 岁",
 "5–14 years": "5–14 岁",
 "≥ 15 years": "≥ 15 岁",
 "Not for children with severe acute malnutrition. See the SAM protocols below.": "不适用于重度急性营养不良（SAM）患儿。见下方SAM方案。",
 "Severity of dehydration": "脱水严重程度",
 "Sign / Symptom": "体征 / 症状",
 "Minimal or No Dehydration": "无脱水或轻微脱水",
 "<3% body weight loss; 3%–5% fluid deficit": "体重丢失 <3%；累积损失 3%–5%",
 "Mild to Moderate Dehydration": "轻至中度脱水",
 "3%–9% body weight loss; 6%–9% fluid deficit": "体重丢失 3%–9%；累积损失 6%–9%",
 "Severe Dehydration": "重度脱水",
 ">9% body weight loss; >10% fluid deficit": "体重丢失 >9%；累积损失 >10%",
 "Mental status": "精神状态",
 "Well; alert": "精神好；警觉",
 "Normal, fatigued, or restless, irritable": "正常、疲乏，或烦躁、易激惹",
 "Apathetic, lethargic, unconscious": "淡漠、嗜睡、意识不清",
 "Drinks normally; might refuse liquids": "饮水正常；可能拒绝饮水",
 "Thirsty; eager to drink": "口渴；急于饮水",
 "Drinks poorly; unable to drink": "饮水差；不能饮水",
 "Heart rate": "心率",
 "Normal to increased": "正常至增快",
 "Tachycardia, with bradycardia in severe cases": "心动过速，重症可出现心动过缓",
 "Quality of pulses": "脉搏强弱",
 "Normal to decreased": "正常至减弱",
 "Weak, thready, or impalpable": "微弱、细弱或触不到",
 "Breathing": "呼吸",
 "Normal; fast": "正常；增快",
 "Deep": "深大",
 "Eyes": "眼睛",
 "Slightly sunken": "轻度凹陷",
 "Deeply sunken": "深度凹陷",
 "Tears": "眼泪",
 "Present": "有",
 "Decreased": "减少",
 "Absent": "无",
 "Mouth and tongue": "口舌",
 "Moist": "湿润",
 "Dry": "干燥",
 "Parched": "干裂",
 "Skin fold": "皮肤皱褶",
 "Instant recoil": "立即回缩",
 "Recoil in <2 s": "<2 秒内回缩",
 "Recoil in >2 s": ">2 秒回缩",
 "Capillary refill": "毛细血管再充盈",
 "Normal (≤ 2 s)": "正常（≤ 2 秒）",
 "Prolonged": "延长",
 "Prolonged; minimal": "延长；极少",
 "Extremities": "四肢",
 "Warm": "温暖",
 "Cool": "凉",
 "Cold; mottled; cyanotic": "冰冷；花斑；发绀",
 "Urine output": "尿量",
 "Minimal": "极少",
 "US framework (CDC/AAP). WHO settings use the A/B/C table above.": "美国体系（CDC/AAP）。采用WHO标准时请使用上方A/B/C表。",
 "Clinical Dehydration Scale (Goldman)": "临床脱水评分（CDS，Goldman）",
 "Characteristic": "项目",
 "General appearance": "一般状态",
 "Thirsty, restless, or lethargic but irritable when touched": "口渴、烦躁，或嗜睡但触碰时易激惹",
 "Drowsy, limp, cold or sweaty ± comatose": "嗜睡、软弱、皮肤冰凉或出汗 ± 昏迷",
 "Extremely sunken": "极度凹陷",
 "Mucous membranes (tongue)": "黏膜（舌）",
 "Sticky": "黏滞",
 "Total Score": "总分",
 "Interpretation": "解读",
 "No dehydration": "无脱水",
 "Some dehydration": "部分脱水",
 "Moderate to severe dehydration": "中至重度脱水",
 "Severe acute malnutrition: who has it?": "重度急性营养不良：诊断标准",
 "Criterion": "标准",
 "Severe (SAM)": "重度（SAM）",
 "Moderate wasting": "中度消瘦",
 "MUAC (6–59 months)": "上臂中围 MUAC（6–59 月龄）",
 "Weight-for-height / length z-score": "身高/身长别体重 z 评分",
 "Bilateral pitting (nutritional) oedema": "双侧凹陷性（营养性）水肿",
 "Any grade (+, ++, +++) = SAM": "任何程度（+、++、+++）= SAM",
 "Rehydration": "补液",
 "SAM protocol (ReSoMal preferred; low-osmolarity ORS if unavailable)": "SAM方案（首选ReSoMal；无则用低渗ORS）",
 "Standard WHO plans with low-osmolarity ORS": "WHO标准方案，使用低渗ORS",
 "Under 6 months: MUAC is not used for SAM; use weight-for-length < −3 SD or oedema. Admit for inpatient care if any IMCI danger sign, acute medical problem, oedema +++, or failed appetite test.": "6 月龄以下：不用MUAC判定SAM；采用身长别体重 < −3 SD或水肿。如有任何IMCI危险征象、急性内科问题、水肿 +++ 或食欲测试未通过，应住院治疗。",
 "Dehydration signs in SAM (≥ 2 signs)": "SAM患儿的脱水体征（≥ 2 项）",
 "Severe dehydration": "重度脱水",
 "No thirst, drinks normally": "不口渴，饮水正常",
 "Unable to drink or drinks poorly": "不能饮水或饮水差",
 "Reduced": "减少",
 "Absent for several hours": "数小时无尿",
 "Recent frequent watery diarrhoea and/or vomiting": "近期频繁水样腹泻和/或呕吐",
 "Yes": "是",
 "Recent obvious rapid weight loss": "近期体重明显快速下降",
 "No": "否",
 "Sunken eyes and a slow skin pinch are often present in SAM without dehydration; oedema can mask dehydration (WHO 2023 B6; MSF 2024).": "SAM患儿即使无脱水也常有眼窝凹陷和皮肤回弹缓慢；水肿可掩盖脱水（WHO 2023 B6；MSF 2024）。",
 "WHO 2013: dehydration is over-diagnosed in SAM. All children with watery diarrhoea or reduced urine output likely have some dehydration; IV only for shock.": "WHO 2013：SAM患儿的脱水常被过度诊断。所有水样腹泻或尿量减少的患儿可能存在部分脱水；仅休克时静脉补液。",
 "ACF 2011: diagnose from the history (recent watery diarrhoea, carer reports the eyes recently sank, no full veins, no oedema); children with oedema cannot be 'dehydrated'.": "ACF 2011：依据病史诊断（近期水样腹泻、照护者诉眼睛近期凹陷、静脉不充盈、无水肿）；有水肿的患儿不能诊断为“脱水”。",
 "SAM rehydration protocols compared": "SAM补液方案比较",
 "WHO 2013/2023 (default)": "WHO 2013/2023（默认）",
 "India 2011": "印度 2011",
 "Oral fluid": "口服补液",
 "Reduced-osmolarity ORS + 15 mL KCl/L": "低渗ORS + 15 mL KCl/L",
 "Some dehydration (oral/NG)": "部分脱水（口服/鼻胃管）",
 "5 mL/kg every 30 min × 2 h, then 5–10 mL/kg/h for 4–10 h alternating with F-75; max 12 h": "每 30 分钟 5 mL/kg × 2 小时，之后 5–10 mL/kg/h，持续 4–10 小时，与F-75交替；最长 12 小时",
 "20 mL/kg/h × 2 h, then 10 mL/kg/h to target weight (current × 1.06)": "20 mL/kg/h × 2 小时，之后 10 mL/kg/h 直至目标体重（当前 × 1.06）",
 "10 mL/kg/h × 2 h, then adjust by hourly weight; stop at target (≤ +5%)": "10 mL/kg/h × 2 小时，之后按每小时称重调整；达目标（≤ +5%）即停",
 "5 mL/kg every 30 min × 2 h, then 5–10 mL/kg alternate hours up to 10 h": "每 30 分钟 5 mL/kg × 2 小时，之后隔小时给予 5–10 mL/kg，最长 10 小时",
 "10 mL/kg/h × 2 h, then 7.5 mL/kg/h alternating with F-75 for 10 h (5–10)": "10 mL/kg/h × 2 小时，之后 7.5 mL/kg/h 与F-75交替，共 10 小时（5–10）",
 "Severe, no shock": "重度，无休克",
 "Same oral regimen; IV (Chart 8) only if oral/NG impossible": "同口服方案；仅在无法口服/鼻胃管时静脉补液（图表 8）",
 "ReSoMal 20 mL/kg over 1 h (target × 1.1); if vomiting G5%-RL 10 mL/kg/h × 2 h": "ReSoMal 20 mL/kg，1 小时内（目标 × 1.1）；如呕吐，G5%-RL 10 mL/kg/h × 2 小时",
 "Same oral regimen": "同口服方案",
 "Shock: IV": "休克：静脉",
 "15 mL/kg over 1 h (RL-5% glucose, ½-Darrow's-5% glucose, or 0.45% NaCl-5% glucose); repeat once if improving, then ReSoMal 10 mL/kg/h": "15 mL/kg，1 小时内（RL-5%葡萄糖、½ Darrow液-5%葡萄糖或 0.45% NaCl-5%葡萄糖）；如有改善重复一次，之后ReSoMal 10 mL/kg/h",
 "Ceftriaxone 80 mg/kg; G5%-RL 10 mL/kg/h × 2 h; reassess at 1 h and 2 h": "头孢曲松 80 mg/kg；G5%-RL 10 mL/kg/h × 2 小时；1 小时和 2 小时时重新评估",
 "15 mL/kg over 1 h (half-strength fluids); repeat while weight is not rising": "15 mL/kg，1 小时内（半张液体）；体重未上升时重复",
 "10% glucose 5 mL/kg; 15 mL/kg over 1 h; repeat once if improving, then ORS 10 mL/kg/h": "10%葡萄糖 5 mL/kg；15 mL/kg，1 小时内；如有改善重复一次，之后ORS 10 mL/kg/h",
 "RL-5% dextrose 20 mL/kg over 2 h": "RL-5%葡萄糖 20 mL/kg，2 小时内",
 "No response": "无反应",
 "After 2 boluses: IV 4 mL/kg/h, whole blood 10 mL/kg over 3 h": "2 次快速输注后：静脉 4 mL/kg/h，全血 10 mL/kg，3 小时内输入",
 "Continue 10 mL/kg/h; check Hb and transfuse": "继续 10 mL/kg/h；查Hb并输血",
 "Weight up but no better: toxic/septic/cardiogenic shock; stop": "体重增加但无好转：中毒性/脓毒性/心源性休克；停止",
 "Septic shock: IV 4 mL/kg/h, review antibiotics, dopamine": "脓毒性休克：静脉 4 mL/kg/h，重新评估抗生素，多巴胺",
 "Severe anaemia: transfuse instead of Ringer's": "重度贫血：输血替代林格液",
 "Stop / overload": "停止 / 容量超负荷",
 "Oral: RR +5 and pulse +25. IV: RR +5 and pulse +15, liver ↑, crackles, JVP ↑, gallop": "口服：呼吸频率 +5 且脉搏 +25。静脉：呼吸频率 +5 且脉搏 +15、肝脏 ↑、湿啰音、颈静脉压 ↑、奔马律",
 "RR ≥ +10 or HR ≥ +20 plus SpO₂ ↓ > 5%, crackles, gallop, liver ↑ or new oedema": "呼吸频率 ≥ +10 或心率 ≥ +20，伴 SpO₂ ↓ > 5%、湿啰音、奔马律、肝脏 ↑ 或新发水肿",
 "Target weight, full veins, oedema, liver +1 cm, RR +5, grunting, crackles, gallop": "达目标体重、静脉充盈、水肿、肝脏 +1 cm、呼吸频率 +5、呻吟、湿啰音、奔马律",
 "RR +5 and pulse +15, jugular veins engorged, puffy eyelids": "呼吸频率 +5 且脉搏 +15、颈静脉怒张、眼睑浮肿",
 "—": "—",
 "Per watery stool": "每次水样便",
 "5 mL/kg (ORS outpatient; ReSoMal inpatient)": "5 mL/kg（门诊用ORS；住院用ReSoMal）",
 "30 mL (6–24 months only)": "30 mL（仅限 6–24 月龄）",
 "< 2 y ~50 mL; ≥ 2 y 100 mL ORS": "< 2 岁约 50 mL；≥ 2 岁 100 mL ORS",
 "Not specified": "未注明",
 "Cholera or profuse watery diarrhoea: standard ORS, not ReSoMal. MSF (SAM + cholera): some dehydration 75 mL/kg ORS over 4 h; severe/shock RL 20 mL/kg over 30 min (up to 3 boluses) then 70 mL/kg over 6 h. Same volume as non-malnourished children, twice as slowly.": "霍乱或大量水样腹泻：用标准ORS，不用ReSoMal。MSF（SAM + 霍乱）：部分脱水 ORS 75 mL/kg，4 小时内；重度/休克 RL 20 mL/kg，30 分钟内（最多快速输注 3 次），之后 70 mL/kg，6 小时内。补液量与非营养不良患儿相同，用时加倍。",
 "Earlier WHO guidance (Treatment of diarrhoea 2005, §8.2) gave 70–100 mL/kg over 12 h, starting at ~10 mL/kg/h; the 2013 Pocket Book regimen above supersedes it.": "WHO早期指南（《腹泻病治疗手册》2005，§8.2）为 70–100 mL/kg，12 小时内输入，起始约 10 mL/kg/h；现以上述 2013 年《袖珍手册》方案为准。",
 "GASTROSAM (2026): in 415 children with SAM and moderate/severe dehydration, standard WHO ORS gave outcomes similar to ReSoMal, with no fluid overload in either arm.": "GASTROSAM（2026）：在 415 名伴中/重度脱水的SAM患儿中，标准WHO ORS的结局与ReSoMal相似，两组均未发生液体超负荷。",
 "ORS Comparison": "ORS比较",
 "ORS Product": "ORS产品",
 "Carbs (g/L)": "碳水化合物（g/L）",
 "Osmolarity (mOsm/L)": "渗透压（mOsm/L）",
 "WHO low-osmolarity (2002)": "WHO低渗配方（2002）",
 "Base (mEq/L)ᵃ": "碱基（mEq/L）ᵃ",
 "ᵃ None of these products contains bicarbonate; the base is citrate (WHO ORS: trisodium citrate 10 mmol/L = 2.9 g/L, about 30 mEq/L of base).": "ᵃ 这些产品均不含碳酸氢盐；碱基为枸橼酸盐（WHO ORS：枸橼酸三钠 10 mmol/L = 2.9 g/L，约 30 mEq/L 碱基）。",
 "WHO low-osmolarity ORS is the formulation in WHO/UNICEF sachets (one sachet per litre of clean water). Check which brands your pharmacy stocks and that they match this composition.": "WHO低渗ORS即WHO/UNICEF袋装配方（每袋兑一升洁净水）。请核实本院药房所备品牌及其成分是否与此一致。",
 "The ESPGHAN option (Na⁺ 60 mEq/L, ~200–250 mOsm/L) can be selected under Institution settings.": "ESPGHAN选项（Na⁺ 60 mEq/L，约 200–250 mOsm/L）可在机构设置中选择。",
 "Commercial products: manufacturer labels.": "市售产品：生产商标签。",
 "ReSoMal and other SAM solutions": "ReSoMal及其他SAM用溶液",
 "Solution": "溶液",
 "Citrate": "枸橼酸盐",
 "Sugars": "糖",
 "Osmolarity": "渗透压",
 "mmol/L unless stated": "除另注明外，单位为 mmol/L",
 "ReSoMal, commercial sachet (84 g in 2 L)": "ReSoMal，市售袋装（84 g 溶于 2 L）",
 "glucose 55, sucrose 73": "葡萄糖 55，蔗糖 73",
 "ReSoMal, WHO recipe from WHO-ORS (2013)": "ReSoMal，以WHO-ORS配制的WHO配方（2013）",
 "+ 50 g sucrose per 2 L": "每 2 L 加蔗糖 50 g",
 "Modified ORS for SAM (WHO 2005)": "SAM用改良ORS（WHO 2005）",
 "+ 25 g/L sugar": "+ 糖 25 g/L",
 "India MoHFW: reduced-osmolarity ORS + 15 mL KCl per litre": "印度MoHFW：低渗ORS + 每升加 15 mL KCl",
 "20 + 20": "20 + 20",
 "glucose 75": "葡萄糖 75",
 "ReSoMal only under medical supervision in a health facility; not for cholera or for uncomplicated malnutrition (use standard ORS). Commercial ReSoMal and ORS are preferred to solutions prepared in the facility or at home.": "ReSoMal仅限在医疗机构内医疗监护下使用；不用于霍乱或无并发症的营养不良（用标准ORS）。市售ReSoMal和ORS优于院内或家庭自配溶液。",
 "“—” = not stated in the source.": "“—”= 来源未注明。",
 "Preparing solutions": "溶液配制",
 "Recipe": "配方",
 "Notes": "备注",
 "Home-made salt–sugar solution": "家庭自制盐糖溶液",
 "3 g/L table salt (one level teaspoon) + 18 g/L sugar (sucrose)": "食盐 3 g/L（一平茶匙）+ 糖（蔗糖）18 g/L",
 "WHO: effective, but not generally recommended. The recipe is often forgotten, ingredients may be unavailable, or too little is given. Prefer ORS; salted home fluids (rice water, soup) are alternatives.": "WHO：有效，但一般不推荐。配方常被遗忘，原料可能缺乏，或给予量过少。首选ORS；加盐的家庭液体（米汤、汤）可作替代。",
 "ReSoMal from WHO-ORS": "以WHO-ORS配制ReSoMal",
 "2 L water + one 1-litre packet WHO-ORS + 50 g sucrose + 40 mL electrolyte/mineral solution (or 45 mL of 10% KCl: 100 g KCl in 1 L)": "水 2 L + 1 升装WHO-ORS一袋 + 蔗糖 50 g + 电解质/矿物质溶液 40 mL（或 10% KCl 45 mL：KCl 100 g 溶于 1 L）",
 "≈ 45 mmol Na, 40 mmol K, 3 mmol Mg per litre (WHO 2013). Not for cholera or profuse watery diarrhoea.": "每升约含 Na 45 mmol、K 40 mmol、Mg 3 mmol（WHO 2013）。不用于霍乱或大量水样腹泻。",
 "Ringer's lactate with 5% glucose (G5%-RL)": "含 5% 葡萄糖的乳酸林格液（G5%-RL）",
 "Remove 50 mL from a 500 mL RL bag; add 50 mL of 50% glucose": "从 500 mL RL袋中抽出 50 mL；加入 50% 葡萄糖 50 mL",
 "MSF 2024; Kenya BPP 2022 (50 mL 50% dextrose + 450 mL RL).": "MSF 2024；肯尼亚 BPP 2022（50% 葡萄糖 50 mL + RL 450 mL）。",
 "RL for cholera infusion (SAM)": "霍乱输液用RL（SAM）",
 "Add 100 mL of 50% glucose to each litre of RL": "每升RL加入 50% 葡萄糖 100 mL",
 "Formulas & code": "公式与代码",
 "Sports Drinks Comparison": "运动饮料比较",
 "Brand": "品牌",
 "Serving": "每份量",
 "Carbs (g)": "碳水化合物（g）",
 "% Carb": "碳水化合物 %",
 "Sugars (g)": "糖（g）",
 "Other Key Ingredients": "其他主要成分",
 "Electrolytes, natural flavor": "电解质，天然香料",
 "Vitamins C, B12, calcium, magnesium": "维生素C、B12，钙，镁",
 "Coconut water, vitamins B3, B5, B6, etc": "椰子水，维生素B3、B5、B6等",
 "Vitamins B6, C, E, niacin, pantothenic acid": "维生素B6、C、E，烟酸，泛酸",
 "Vitamins B, C, E": "维生素B、C、E",
 "Magnesium, calcium": "镁，钙",
 "Vitamins B12, C, calcium, magnesium": "维生素B12、C，钙，镁",
 "Zinc, chloride 440 mg, zinc 2.8 mg": "锌，氯化物 440 mg，锌 2.8 mg",
 "Vitamin C, calcium, magnesium": "维生素C，钙，镁",
 "Ca 47 mg, Mg 100 mg, Zn 1 mg, Cl 78 mg, Mn 0.2 mg, vitamin C 100 mg": "Ca 47 mg，Mg 100 mg，Zn 1 mg，Cl 78 mg，Mn 0.2 mg，维生素C 100 mg",
 "a BodyArmor Lyte: serving size (12 oz) from website; nutrition label did not specify which size.": "a BodyArmor Lyte：每份量（12 oz）取自官网；营养标签未注明规格。",
 "b Nuun Sport: product supplied as a dissolvable tablet.": "b Nuun Sport：可溶片剂型。",
 "c Skratch Labs Sport Hydration Mix: product supplied as a powder mixture.": "c Skratch Labs Sport Hydration Mix：粉末冲剂型。",
 "d Ultima Replenisher: composition reported per scoop.": "d Ultima Replenisher：成分按每勺计。",
 "Sports drinks are not oral rehydration solutions; compare their sodium and sugar with the ORS table above.": "运动饮料不是口服补液溶液；请将其钠和糖含量与上方ORS表比较。",
 "Manufacturer nutrition labels; data as published.": "生产商营养标签；数据按公开发布原样列出。",
 "Holliday–Segar: 100 mL/kg for the first 10 kg + 50 mL/kg for the next 10 kg + 20 mL/kg per kg above 20; hourly = daily ÷ 24.": "Holliday–Segar：前 10 kg 按 100 mL/kg + 其后 10 kg 按 50 mL/kg + 超过 20 kg 部分每 kg 20 mL/kg；每小时量 = 每日量 ÷ 24。",
 "Deficit (mL) = deficit % × weight (kg) × 10 (1% of body weight ≈ 10 mL/kg).": "累积损失量（mL）= 脱水百分比 × 体重（kg）× 10（体重的 1% ≈ 10 mL/kg）。",
 "% dehydration = (well weight − current weight) ÷ well weight × 100, capped at 15%.": "脱水 % =（健康体重 − 当前体重）÷ 健康体重 × 100，上限 15%。",
 "10 mL/kg per watery stool + 2 mL/kg per emesis.": "每次水样便 10 mL/kg + 每次呕吐 2 mL/kg。",
 "Goldman CDS: sum of 4 items (0–2 each); 0 none, 1–4 some, 5–8 moderate/severe.": "Goldman CDS：4 项之和（每项 0–2）；0 无，1–4 部分，5–8 中/重度。",
 "WHO: ≥ 2 signs in column C = severe; ≥ 2 signs in B or C = some; otherwise none.": "WHO：C栏 ≥ 2 项体征 = 重度；B或C栏 ≥ 2 项 = 部分；否则无。",
 "ORS volume = rate (mL/kg, WHO 75) × weight, over the chosen hours.": "ORS量 = 剂量（mL/kg，WHO 75）× 体重，在所选时长内给予。",
 "WHO Plan C: 100 mL/kg = 30 mL/kg then 70 mL/kg; < 12 months over 1 h + 5 h, older over 30 min + 2.5 h.": "WHO方案C：100 mL/kg = 30 mL/kg 后 70 mL/kg；< 12 月龄 1 小时 + 5 小时，年长儿 30 分钟 + 2.5 小时。",
 "Bolus-first: 20 mL/kg boluses; phase 2 = (deficit − boluses given) + 12 h maintenance, over 12 h.": "快速输注优先：每次 20 mL/kg；第2阶段 =（累积损失量 − 已快速输注量）+ 12 小时维持量，12 小时内输入。",
 "Zinc for acute diarrhoea: 10 mg/day under 6 months, 20 mg/day from 6 months, for 10–14 days.": "急性腹泻补锌：6 月龄以下 10 mg/天，6 月龄起 20 mg/天，连用 10–14 天。",
 "SAM if MUAC < 115 mm (6–59 months), weight-for-height < −3 SD, or bilateral pitting oedema.": "符合任一即为SAM：MUAC < 115 mm（6–59 月龄）、身高别体重 < −3 SD 或双侧凹陷性水肿。",
 "mL": "mL",
 "< 5 kg": "< 5 kg",
 "5–7.9 kg": "5–7.9 kg",
 "8–10.9 kg": "8–10.9 kg",
 "11–15.9 kg": "11–15.9 kg",
 "16–29.9 kg": "16–29.9 kg",
 "≥ 30 kg": "≥ 30 kg",
 "< 115 mm": "< 115 mm",
 "115 – < 125 mm": "115 – < 125 mm",
 "< −3 SD": "< −3 SD",
 "−3 to < −2 SD": "−3 至 < −2 SD",
 "50–100 mL ReSoMal": "ReSoMal 50–100 mL",
 "Cal": "热量",
 "MSF cholera §5.8.": "MSF 霍乱 §5.8."
};
