/* PRhehydrate — Russian strings for tables.html, keyed by the English text in js/tables.js. */
window.RH_TABLES_RU = {
 "Clinical Reference Tables": "Клинические справочные таблицы",
 "Back to calculator": "Назад к калькулятору",
 "Source": "Источник",
 "Sources": "Источники",
 "For clinical reference only. Verify all values against current authoritative sources before use. PRhehydrate is not a substitute for clinical judgment.": "Только для клинической справки. Перед применением сверяйте все значения с актуальными авторитетными источниками. PRhehydrate не заменяет клиническое суждение.",
 "Source code": "Исходный код",
 "SAM protocol: ": "Протокол ТОНП: ",
 "Theme and language": "Тема и язык",
 "Color theme": "Цветовая тема",
 "Change language": "Сменить язык",
 "WHO: Assessing dehydration": "ВОЗ: оценка обезвоживания",
 "Sign": "Признак",
 "A: No dehydration": "A: Обезвоживания нет",
 "B: Some dehydration": "B: Умеренное обезвоживание",
 "C: Severe dehydration": "C: Тяжёлое обезвоживание",
 "Condition¹": "Общее состояние¹",
 "Well, alert": "Хорошее, в ясном сознании",
 "Restless, irritable": "Беспокоен, раздражителен",
 "Lethargic or unconscious": "Заторможен или без сознания",
 "Eyes²": "Глаза²",
 "Normal": "Норма",
 "Sunken": "Запавшие",
 "Thirst": "Жажда",
 "Drinks normally, not thirsty": "Пьёт нормально, жажды нет",
 "Thirsty, drinks eagerly": "Жажда, пьёт с жадностью",
 "Drinks poorly or not able to drink": "Пьёт плохо или не может пить",
 "Skin pinch³": "Кожная складка³",
 "Goes back quickly": "Расправляется быстро",
 "Goes back slowly": "Расправляется медленно",
 "Goes back very slowly (≥ 2 s)": "Расправляется очень медленно (≥ 2 с)",
 "Decide": "Вывод",
 "Not enough signs for B or C": "Недостаточно признаков для B или C",
 "Two or more signs in B": "Два и более признака из B",
 "Two or more signs in C": "Два и более признака из C",
 "Treat": "Лечение",
 "Plan A": "План A",
 "Weigh; Plan B": "Взвесить; План B",
 "Weigh; Plan C urgently": "Взвесить; срочно План C",
 "¹ Lethargic is not the same as asleep: the child's mental state is dull and the child cannot be fully awakened.": "¹ Заторможенность — не то же, что сон: сознание угнетено, ребёнка невозможно полностью разбудить.",
 "² In some children the eyes are normally somewhat sunken. Ask the mother whether they look different than usual.": "² У некоторых детей глаза в норме слегка запавшие. Спросите мать, выглядят ли они иначе, чем обычно.",
 "³ The skin pinch is less useful in marasmus, kwashiorkor or obese children. See the SAM tables below.": "³ Кожная складка менее информативна при маразме, квашиоркоре и ожирении. См. таблицы по ТОНП ниже.",
 "WHO: Treatment plans A, B and C": "ВОЗ: планы лечения A, B и C",
 "Plan": "План",
 "What to give": "Что давать",
 "A: no dehydration": "A: обезвоживания нет",
 "Extra fluid after each loose stool: < 2 years 50–100 mL; ≥ 2 years 100–200 mL. Zinc 10–14 days: ≤ 6 months 10 mg/day, ≥ 6 months 20 mg/day. Continue feeding.": "Дополнительная жидкость после каждого жидкого стула: < 2 лет 50–100 мл; ≥ 2 лет 100–200 мл. Цинк 10–14 дней: ≤ 6 мес. 10 мг/сут, ≥ 6 мес. 20 мг/сут. Продолжать кормление.",
 "B: some dehydration": "B: умеренное обезвоживание",
 "ORS 75 mL/kg over 4 h (give more if the child wants more). Reassess at 4 h.": "ОРС 75 мл/кг за 4 ч (давать больше, если ребёнок хочет). Повторная оценка через 4 ч.",
 "C: severe dehydration": "C: тяжёлое обезвоживание",
 "IV Ringer's lactate (or normal saline) 100 mL/kg: 30 mL/kg then 70 mL/kg. Infants < 12 months: 1 h + 5 h. Older: 30 min + 2.5 h. Repeat the first portion if the radial pulse is still very weak. ORS ~5 mL/kg/h as soon as the child can drink.": "В/в раствор Рингера лактат (или 0,9% NaCl) 100 мл/кг: 30 мл/кг, затем 70 мл/кг. Дети < 12 мес.: 1 ч + 5 ч. Старше: 30 мин + 2,5 ч. Повторить первую порцию, если пульс на лучевой артерии остаётся очень слабым. ОРС ~5 мл/кг/ч, как только ребёнок сможет пить.",
 "Plan B: approximate ORS in the first 4 hours (use age only if weight is unknown; otherwise weight × 75)": "План B: ориентировочный объём ОРС за первые 4 часа (возраст — только если масса неизвестна; иначе масса × 75)",
 "Age": "Возраст",
 "Weight": "Масса тела",
 "< 4 months": "< 4 мес.",
 "4–11 months": "4–11 мес.",
 "12–23 months": "12–23 мес.",
 "2–4 years": "2–4 года",
 "5–14 years": "5–14 лет",
 "≥ 15 years": "≥ 15 лет",
 "Not for children with severe acute malnutrition. See the SAM protocols below.": "Не для детей с тяжёлой острой недостаточностью питания. См. протоколы ТОНП ниже.",
 "Severity of dehydration": "Степень обезвоживания",
 "Sign / Symptom": "Признак / симптом",
 "Minimal or No Dehydration": "Минимальное обезвоживание или его отсутствие",
 "<3% body weight loss; 3%–5% fluid deficit": "потеря <3% массы тела; дефицит жидкости 3%–5%",
 "Mild to Moderate Dehydration": "Лёгкое или среднетяжёлое обезвоживание",
 "3%–9% body weight loss; 6%–9% fluid deficit": "потеря 3%–9% массы тела; дефицит жидкости 6%–9%",
 "Severe Dehydration": "Тяжёлое обезвоживание",
 ">9% body weight loss; >10% fluid deficit": "потеря >9% массы тела; дефицит жидкости >10%",
 "Mental status": "Психический статус",
 "Well; alert": "Хорошее; ясное сознание",
 "Normal, fatigued, or restless, irritable": "Норма, утомлён или беспокоен, раздражителен",
 "Apathetic, lethargic, unconscious": "Апатия, заторможенность, без сознания",
 "Drinks normally; might refuse liquids": "Пьёт нормально; может отказываться от жидкости",
 "Thirsty; eager to drink": "Жажда; пьёт с жадностью",
 "Drinks poorly; unable to drink": "Пьёт плохо; не может пить",
 "Heart rate": "ЧСС",
 "Normal to increased": "Норма или повышение",
 "Tachycardia, with bradycardia in severe cases": "Тахикардия, в тяжёлых случаях брадикардия",
 "Quality of pulses": "Наполнение пульса",
 "Normal to decreased": "Норма или снижение",
 "Weak, thready, or impalpable": "Слабый, нитевидный или не пальпируется",
 "Breathing": "Дыхание",
 "Normal; fast": "Норма; учащённое",
 "Deep": "Глубокое",
 "Eyes": "Глаза",
 "Slightly sunken": "Слегка запавшие",
 "Deeply sunken": "Глубоко запавшие",
 "Tears": "Слёзы",
 "Present": "Есть",
 "Decreased": "Снижение",
 "Absent": "Нет",
 "Mouth and tongue": "Рот и язык",
 "Moist": "Влажные",
 "Dry": "Сухие",
 "Parched": "Пересохшие",
 "Skin fold": "Кожная складка",
 "Instant recoil": "Расправляется сразу",
 "Recoil in <2 s": "Расправляется за <2 с",
 "Recoil in >2 s": "Расправляется за >2 с",
 "Capillary refill": "Время наполнения капилляров",
 "Normal (≤ 2 s)": "Норма (≤ 2 с)",
 "Prolonged": "Удлинено",
 "Prolonged; minimal": "Удлинено; минимально",
 "Extremities": "Конечности",
 "Warm": "Тёплые",
 "Cool": "Прохладные",
 "Cold; mottled; cyanotic": "Холодные; мраморные; цианотичные",
 "Urine output": "Диурез",
 "Minimal": "Минимальный",
 "US framework (CDC/AAP). WHO settings use the A/B/C table above.": "Подход США (CDC/AAP). Там, где применяются рекомендации ВОЗ, используйте таблицу A/B/C выше.",
 "Clinical Dehydration Scale (Goldman)": "Клиническая шкала обезвоживания (Goldman)",
 "Characteristic": "Признак",
 "General appearance": "Общий вид",
 "Thirsty, restless, or lethargic but irritable when touched": "Жажда, беспокоен или заторможен, но раздражителен при прикосновении",
 "Drowsy, limp, cold or sweaty ± comatose": "Сонлив, вял, кожа холодная или потная ± кома",
 "Extremely sunken": "Резко запавшие",
 "Mucous membranes (tongue)": "Слизистые оболочки (язык)",
 "Sticky": "Липкие",
 "Total Score": "Сумма баллов",
 "Interpretation": "Интерпретация",
 "No dehydration": "Обезвоживания нет",
 "Some dehydration": "Умеренное обезвоживание",
 "Moderate to severe dehydration": "Среднетяжёлое или тяжёлое обезвоживание",
 "Severe acute malnutrition: who has it?": "Тяжёлая острая недостаточность питания: критерии",
 "Criterion": "Критерий",
 "Severe (SAM)": "Тяжёлая (ТОНП)",
 "Moderate wasting": "Умеренное истощение",
 "MUAC (6–59 months)": "ОСП (6–59 мес.)",
 "Weight-for-height / length z-score": "Z-оценка массы тела к росту / длине тела",
 "Bilateral pitting (nutritional) oedema": "Двусторонние (алиментарные) отёки (симптом ямки)",
 "Any grade (+, ++, +++) = SAM": "Любой степени (+, ++, +++) = ТОНП",
 "Rehydration": "Регидратация",
 "SAM protocol (ReSoMal preferred; low-osmolarity ORS if unavailable)": "Протокол ТОНП (предпочтительно ReSoMal; при его отсутствии — ОРС пониженной осмолярности)",
 "Standard WHO plans with low-osmolarity ORS": "Стандартные планы ВОЗ с ОРС пониженной осмолярности",
 "Under 6 months: MUAC is not used for SAM; use weight-for-length < −3 SD or oedema. Admit for inpatient care if any IMCI danger sign, acute medical problem, oedema +++, or failed appetite test.": "Младше 6 мес.: ОСП для диагностики ТОНП не используется; ориентируйтесь на массу тела к длине тела < −3 SD или отёки. Госпитализировать при любом общем признаке опасности ИВБДВ, остром заболевании, отёках +++ или непройденном тесте на аппетит.",
 "Dehydration signs in SAM (≥ 2 signs)": "Признаки обезвоживания при ТОНП (≥ 2 признаков)",
 "Severe dehydration": "Тяжёлое обезвоживание",
 "No thirst, drinks normally": "Жажды нет, пьёт нормально",
 "Unable to drink or drinks poorly": "Не может пить или пьёт плохо",
 "Reduced": "Снижен",
 "Absent for several hours": "Отсутствует несколько часов",
 "Recent frequent watery diarrhoea and/or vomiting": "Недавняя частая водянистая диарея и/или рвота",
 "Yes": "Да",
 "Recent obvious rapid weight loss": "Недавняя явная быстрая потеря массы тела",
 "No": "Нет",
 "Sunken eyes and a slow skin pinch are often present in SAM without dehydration; oedema can mask dehydration (WHO 2023 B6; MSF 2024).": "Запавшие глаза и медленно расправляющаяся кожная складка часто встречаются при ТОНП без обезвоживания; отёки могут маскировать обезвоживание (ВОЗ 2023 B6; MSF 2024).",
 "WHO 2013: dehydration is over-diagnosed in SAM. All children with watery diarrhoea or reduced urine output likely have some dehydration; IV only for shock.": "ВОЗ 2013: при ТОНП обезвоживание диагностируют избыточно. У всех детей с водянистой диареей или сниженным диурезом вероятно умеренное обезвоживание; в/в — только при шоке.",
 "ACF 2011: diagnose from the history (recent watery diarrhoea, carer reports the eyes recently sank, no full veins, no oedema); children with oedema cannot be 'dehydrated'.": "ACF 2011: диагноз по анамнезу (недавняя водянистая диарея, по словам ухаживающего, глаза недавно запали, нет набухших вен, нет отёков); дети с отёками не могут считаться «обезвоженными».",
 "SAM rehydration protocols compared": "Протоколы регидратации при ТОНП: сравнение",
 "WHO 2013/2023 (default)": "ВОЗ 2013/2023 (по умолчанию)",
 "India 2011": "Индия 2011",
 "Oral fluid": "Раствор для приёма внутрь",
 "Reduced-osmolarity ORS + 15 mL KCl/L": "ОРС пониженной осмолярности + 15 мл KCl/л",
 "Some dehydration (oral/NG)": "Умеренное обезвоживание (внутрь/НГЗ)",
 "5 mL/kg every 30 min × 2 h, then 5–10 mL/kg/h for 4–10 h alternating with F-75; max 12 h": "5 мл/кг каждые 30 мин × 2 ч, затем 5–10 мл/кг/ч в течение 4–10 ч, чередуя с F-75; макс. 12 ч",
 "20 mL/kg/h × 2 h, then 10 mL/kg/h to target weight (current × 1.06)": "20 мл/кг/ч × 2 ч, затем 10 мл/кг/ч до целевой массы (текущая × 1,06)",
 "10 mL/kg/h × 2 h, then adjust by hourly weight; stop at target (≤ +5%)": "10 мл/кг/ч × 2 ч, затем коррекция по ежечасному взвешиванию; остановить при целевой массе (≤ +5%)",
 "5 mL/kg every 30 min × 2 h, then 5–10 mL/kg alternate hours up to 10 h": "5 мл/кг каждые 30 мин × 2 ч, затем 5–10 мл/кг через час, до 10 ч",
 "10 mL/kg/h × 2 h, then 7.5 mL/kg/h alternating with F-75 for 10 h (5–10)": "10 мл/кг/ч × 2 ч, затем 7,5 мл/кг/ч, чередуя с F-75, в течение 10 ч (5–10)",
 "Severe, no shock": "Тяжёлое, без шока",
 "Same oral regimen; IV (Chart 8) only if oral/NG impossible": "Та же схема внутрь; в/в (Chart 8) — только если внутрь/через НГЗ невозможно",
 "ReSoMal 20 mL/kg over 1 h (target × 1.1); if vomiting G5%-RL 10 mL/kg/h × 2 h": "ReSoMal 20 мл/кг за 1 ч (цель × 1,1); при рвоте G5%-RL 10 мл/кг/ч × 2 ч",
 "Same oral regimen": "Та же схема внутрь",
 "Shock: IV": "Шок: в/в",
 "15 mL/kg over 1 h (RL-5% glucose, ½-Darrow's-5% glucose, or 0.45% NaCl-5% glucose); repeat once if improving, then ReSoMal 10 mL/kg/h": "15 мл/кг за 1 ч (RL + 5% глюкоза, ½ раствора Дарроу + 5% глюкоза или 0,45% NaCl + 5% глюкоза); при улучшении повторить однократно, затем ReSoMal 10 мл/кг/ч",
 "Ceftriaxone 80 mg/kg; G5%-RL 10 mL/kg/h × 2 h; reassess at 1 h and 2 h": "Цефтриаксон 80 мг/кг; G5%-RL 10 мл/кг/ч × 2 ч; повторная оценка через 1 ч и 2 ч",
 "15 mL/kg over 1 h (half-strength fluids); repeat while weight is not rising": "15 мл/кг за 1 ч (растворы половинной концентрации); повторять, пока масса тела не растёт",
 "10% glucose 5 mL/kg; 15 mL/kg over 1 h; repeat once if improving, then ORS 10 mL/kg/h": "10% глюкоза 5 мл/кг; 15 мл/кг за 1 ч; при улучшении повторить однократно, затем ОРС 10 мл/кг/ч",
 "RL-5% dextrose 20 mL/kg over 2 h": "RL + 5% декстроза 20 мл/кг за 2 ч",
 "No response": "Нет ответа",
 "After 2 boluses: IV 4 mL/kg/h, whole blood 10 mL/kg over 3 h": "После 2 болюсов: в/в 4 мл/кг/ч, цельная кровь 10 мл/кг за 3 ч",
 "Continue 10 mL/kg/h; check Hb and transfuse": "Продолжать 10 мл/кг/ч; определить Hb и перелить кровь",
 "Weight up but no better: toxic/septic/cardiogenic shock; stop": "Масса растёт без улучшения: токсический/септический/кардиогенный шок; остановить",
 "Septic shock: IV 4 mL/kg/h, review antibiotics, dopamine": "Септический шок: в/в 4 мл/кг/ч, пересмотреть антибиотики, допамин",
 "Severe anaemia: transfuse instead of Ringer's": "Тяжёлая анемия: гемотрансфузия вместо раствора Рингера",
 "Stop / overload": "Остановка / перегрузка",
 "Oral: RR +5 and pulse +25. IV: RR +5 and pulse +15, liver ↑, crackles, JVP ↑, gallop": "Внутрь: ЧД +5 и пульс +25. В/в: ЧД +5 и пульс +15, печень ↑, крепитация, набухание яремных вен, ритм галопа",
 "RR ≥ +10 or HR ≥ +20 plus SpO₂ ↓ > 5%, crackles, gallop, liver ↑ or new oedema": "ЧД ≥ +10 или ЧСС ≥ +20, а также SpO₂ ↓ > 5%, крепитация, ритм галопа, печень ↑ или новые отёки",
 "Target weight, full veins, oedema, liver +1 cm, RR +5, grunting, crackles, gallop": "Целевая масса, набухшие вены, отёки, печень +1 см, ЧД +5, стонущее дыхание, крепитация, ритм галопа",
 "RR +5 and pulse +15, jugular veins engorged, puffy eyelids": "ЧД +5 и пульс +15, набухание яремных вен, отёчность век",
 "—": "—",
 "Per watery stool": "На каждый водянистый стул",
 "5 mL/kg (ORS outpatient; ReSoMal inpatient)": "5 мл/кг (амбулаторно ОРС; в стационаре ReSoMal)",
 "30 mL (6–24 months only)": "30 мл (только 6–24 мес.)",
 "< 2 y ~50 mL; ≥ 2 y 100 mL ORS": "< 2 лет ~50 мл; ≥ 2 лет 100 мл ОРС",
 "Not specified": "Не указано",
 "Cholera or profuse watery diarrhoea: standard ORS, not ReSoMal. MSF (SAM + cholera): some dehydration 75 mL/kg ORS over 4 h; severe/shock RL 20 mL/kg over 30 min (up to 3 boluses) then 70 mL/kg over 6 h. Same volume as non-malnourished children, twice as slowly.": "Холера или обильная водянистая диарея: стандартный ОРС, не ReSoMal. MSF (ТОНП + холера): умеренное обезвоживание — ОРС 75 мл/кг за 4 ч; тяжёлое/шок — RL 20 мл/кг за 30 мин (до 3 болюсов), затем 70 мл/кг за 6 ч. Тот же объём, что у детей без недостаточности питания, но вдвое медленнее.",
 "Earlier WHO guidance (Treatment of diarrhoea 2005, §8.2) gave 70–100 mL/kg over 12 h, starting at ~10 mL/kg/h; the 2013 Pocket Book regimen above supersedes it.": "Прежние рекомендации ВОЗ (Treatment of diarrhoea 2005, §8.2): 70–100 мл/кг за 12 ч, начиная с ~10 мл/кг/ч; их заменяет схема Pocket Book 2013, приведённая выше.",
 "GASTROSAM (2026): in 415 children with SAM and moderate/severe dehydration, standard WHO ORS gave outcomes similar to ReSoMal, with no fluid overload in either arm.": "GASTROSAM (2026): у 415 детей с ТОНП и среднетяжёлым/тяжёлым обезвоживанием стандартный ОРС ВОЗ дал результаты, сходные с ReSoMal, без перегрузки жидкостью ни в одной из групп.",
 "ORS Comparison": "Сравнение ОРС",
 "ORS Product": "Препарат ОРС",
 "Carbs (g/L)": "Углеводы (г/л)",
 "Osmolarity (mOsm/L)": "Осмолярность (мОсм/л)",
 "WHO low-osmolarity (2002)": "ВОЗ, пониженной осмолярности (2002)",
 "Base (mEq/L)ᵃ": "Основания (мЭкв/л)ᵃ",
 "ᵃ None of these products contains bicarbonate; the base is citrate (WHO ORS: trisodium citrate 10 mmol/L = 2.9 g/L, about 30 mEq/L of base).": "ᵃ Ни один из этих препаратов не содержит бикарбонат; основание — цитрат (ОРС ВОЗ: тринатрия цитрат 10 ммоль/л = 2,9 г/л, около 30 мЭкв/л оснований).",
 "WHO low-osmolarity ORS is the formulation in WHO/UNICEF sachets (one sachet per litre of clean water). Check which brands your pharmacy stocks and that they match this composition.": "ОРС ВОЗ пониженной осмолярности — состав пакетов ВОЗ/ЮНИСЕФ (один пакет на литр чистой воды). Проверьте, какие марки есть в вашей аптеке и соответствуют ли они этому составу.",
 "The ESPGHAN option (Na⁺ 60 mEq/L, ~200–250 mOsm/L) can be selected under Institution settings.": "Вариант ESPGHAN (Na⁺ 60 мЭкв/л, ~200–250 мОсм/л) можно выбрать в настройках учреждения.",
 "Commercial products: manufacturer labels.": "Коммерческие препараты: маркировка производителей.",
 "ReSoMal and other SAM solutions": "ReSoMal и другие растворы при ТОНП",
 "Solution": "Раствор",
 "Citrate": "Цитрат",
 "Sugars": "Сахара",
 "Osmolarity": "Осмолярность",
 "mmol/L unless stated": "ммоль/л, если не указано иное",
 "ReSoMal, commercial sachet (84 g in 2 L)": "ReSoMal, промышленный пакет (84 г на 2 л)",
 "glucose 55, sucrose 73": "глюкоза 55, сахароза 73",
 "ReSoMal, WHO recipe from WHO-ORS (2013)": "ReSoMal, рецепт ВОЗ на основе ОРС ВОЗ (2013)",
 "+ 50 g sucrose per 2 L": "+ 50 г сахарозы на 2 л",
 "Modified ORS for SAM (WHO 2005)": "Модифицированный ОРС для ТОНП (ВОЗ 2005)",
 "+ 25 g/L sugar": "+ 25 г/л сахара",
 "India MoHFW: reduced-osmolarity ORS + 15 mL KCl per litre": "Минздрав Индии: ОРС пониженной осмолярности + 15 мл KCl на литр",
 "20 + 20": "20 + 20",
 "glucose 75": "глюкоза 75",
 "ReSoMal only under medical supervision in a health facility; not for cholera or for uncomplicated malnutrition (use standard ORS). Commercial ReSoMal and ORS are preferred to solutions prepared in the facility or at home.": "ReSoMal — только под медицинским наблюдением в медицинском учреждении; не при холере и не при неосложнённой недостаточности питания (используйте стандартный ОРС). Промышленные ReSoMal и ОРС предпочтительнее растворов, приготовленных в учреждении или дома.",
 "“—” = not stated in the source.": "«—» = не указано в источнике.",
 "Preparing solutions": "Приготовление растворов",
 "Recipe": "Рецепт",
 "Notes": "Примечания",
 "Home-made salt–sugar solution": "Домашний солево-сахарный раствор",
 "3 g/L table salt (one level teaspoon) + 18 g/L sugar (sucrose)": "3 г/л поваренной соли (одна чайная ложка без верха) + 18 г/л сахара (сахарозы)",
 "WHO: effective, but not generally recommended. The recipe is often forgotten, ingredients may be unavailable, or too little is given. Prefer ORS; salted home fluids (rice water, soup) are alternatives.": "ВОЗ: эффективен, но в целом не рекомендуется. Рецепт часто забывают, ингредиентов может не быть, или дают слишком мало. Предпочтителен ОРС; альтернативы — подсоленные домашние жидкости (рисовый отвар, суп).",
 "ReSoMal from WHO-ORS": "ReSoMal из ОРС ВОЗ",
 "2 L water + one 1-litre packet WHO-ORS + 50 g sucrose + 40 mL electrolyte/mineral solution (or 45 mL of 10% KCl: 100 g KCl in 1 L)": "2 л воды + один пакет ОРС ВОЗ на 1 л + 50 г сахарозы + 40 мл электролитно-минерального раствора (или 45 мл 10% KCl: 100 г KCl на 1 л)",
 "≈ 45 mmol Na, 40 mmol K, 3 mmol Mg per litre (WHO 2013). Not for cholera or profuse watery diarrhoea.": "≈ 45 ммоль Na, 40 ммоль K, 3 ммоль Mg на литр (ВОЗ 2013). Не при холере и обильной водянистой диарее.",
 "Ringer's lactate with 5% glucose (G5%-RL)": "Раствор Рингера лактат с 5% глюкозой (G5%-RL)",
 "Remove 50 mL from a 500 mL RL bag; add 50 mL of 50% glucose": "Удалить 50 мл из пакета RL 500 мл; добавить 50 мл 50% глюкозы",
 "MSF 2024; Kenya BPP 2022 (50 mL 50% dextrose + 450 mL RL).": "MSF 2024; Kenya BPP 2022 (50 мл 50% декстрозы + 450 мл RL).",
 "RL for cholera infusion (SAM)": "RL для инфузии при холере (ТОНП)",
 "Add 100 mL of 50% glucose to each litre of RL": "Добавить 100 мл 50% глюкозы на каждый литр RL",
 "Formulas & code": "Формулы и код",
 "Sports Drinks Comparison": "Сравнение спортивных напитков",
 "Brand": "Марка",
 "Serving": "Порция",
 "Carbs (g)": "Углеводы (г)",
 "% Carb": "% углеводов",
 "Sugars (g)": "Сахара (г)",
 "Other Key Ingredients": "Другие основные компоненты",
 "Electrolytes, natural flavor": "Электролиты, натуральный ароматизатор",
 "Vitamins C, B12, calcium, magnesium": "Витамины C, B12, кальций, магний",
 "Coconut water, vitamins B3, B5, B6, etc": "Кокосовая вода, витамины B3, B5, B6 и др.",
 "Vitamins B6, C, E, niacin, pantothenic acid": "Витамины B6, C, E, ниацин, пантотеновая кислота",
 "Vitamins B, C, E": "Витамины B, C, E",
 "Magnesium, calcium": "Магний, кальций",
 "Vitamins B12, C, calcium, magnesium": "Витамины B12, C, кальций, магний",
 "Zinc, chloride 440 mg, zinc 2.8 mg": "Цинк, хлорид 440 мг, цинк 2,8 мг",
 "Vitamin C, calcium, magnesium": "Витамин C, кальций, магний",
 "Ca 47 mg, Mg 100 mg, Zn 1 mg, Cl 78 mg, Mn 0.2 mg, vitamin C 100 mg": "Ca 47 мг, Mg 100 мг, Zn 1 мг, Cl 78 мг, Mn 0,2 мг, витамин C 100 мг",
 "a BodyArmor Lyte: serving size (12 oz) from website; nutrition label did not specify which size.": "a BodyArmor Lyte: размер порции (12 oz) по данным сайта; на этикетке размер не указан.",
 "b Nuun Sport: product supplied as a dissolvable tablet.": "b Nuun Sport: выпускается в виде растворимой таблетки.",
 "c Skratch Labs Sport Hydration Mix: product supplied as a powder mixture.": "c Skratch Labs Sport Hydration Mix: выпускается в виде порошка для разведения.",
 "d Ultima Replenisher: composition reported per scoop.": "d Ultima Replenisher: состав указан на одну мерную ложку.",
 "Sports drinks are not oral rehydration solutions; compare their sodium and sugar with the ORS table above.": "Спортивные напитки не являются растворами для оральной регидратации; сравните содержание натрия и сахара с таблицей ОРС выше.",
 "Manufacturer nutrition labels; data as published.": "Пищевая маркировка производителей; данные в опубликованном виде.",
 "Holliday–Segar: 100 mL/kg for the first 10 kg + 50 mL/kg for the next 10 kg + 20 mL/kg per kg above 20; hourly = daily ÷ 24.": "Holliday–Segar: 100 мл/кг на первые 10 кг + 50 мл/кг на следующие 10 кг + 20 мл/кг на каждый кг свыше 20; в час = в сутки ÷ 24.",
 "Deficit (mL) = deficit % × weight (kg) × 10 (1% of body weight ≈ 10 mL/kg).": "Дефицит (мл) = дефицит % × масса (кг) × 10 (1% массы тела ≈ 10 мл/кг).",
 "% dehydration = (well weight − current weight) ÷ well weight × 100, capped at 15%.": "% обезвоживания = (масса до болезни − текущая масса) ÷ масса до болезни × 100, не более 15%.",
 "10 mL/kg per watery stool + 2 mL/kg per emesis.": "10 мл/кг на каждый водянистый стул + 2 мл/кг на каждую рвоту.",
 "Goldman CDS: sum of 4 items (0–2 each); 0 none, 1–4 some, 5–8 moderate/severe.": "КШО Goldman: сумма 4 пунктов (каждый 0–2); 0 — нет, 1–4 — умеренное, 5–8 — среднетяжёлое/тяжёлое.",
 "WHO: ≥ 2 signs in column C = severe; ≥ 2 signs in B or C = some; otherwise none.": "ВОЗ: ≥ 2 признаков в столбце C = тяжёлое; ≥ 2 признаков в B или C = умеренное; иначе — нет.",
 "ORS volume = rate (mL/kg, WHO 75) × weight, over the chosen hours.": "Объём ОРС = доза (мл/кг, ВОЗ 75) × масса, за выбранное число часов.",
 "WHO Plan C: 100 mL/kg = 30 mL/kg then 70 mL/kg; < 12 months over 1 h + 5 h, older over 30 min + 2.5 h.": "План C ВОЗ: 100 мл/кг = 30 мл/кг, затем 70 мл/кг; < 12 мес. за 1 ч + 5 ч, старше — за 30 мин + 2,5 ч.",
 "Bolus-first: 20 mL/kg boluses; phase 2 = (deficit − boluses given) + 12 h maintenance, over 12 h.": "Сначала болюсы: болюсы по 20 мл/кг; фаза 2 = (дефицит − введённые болюсы) + поддерживающий объём на 12 ч, за 12 ч.",
 "Zinc for acute diarrhoea: 10 mg/day under 6 months, 20 mg/day from 6 months, for 10–14 days.": "Цинк при острой диарее: 10 мг/сут до 6 мес., 20 мг/сут с 6 мес., в течение 10–14 дней.",
 "SAM if MUAC < 115 mm (6–59 months), weight-for-height < −3 SD, or bilateral pitting oedema.": "ТОНП, если ОСП < 115 мм (6–59 мес.), масса тела к росту < −3 SD или двусторонние отёки (симптом ямки).",
 "mL": "мл",
 "< 5 kg": "< 5 кг",
 "5–7.9 kg": "5–7,9 кг",
 "8–10.9 kg": "8–10,9 кг",
 "11–15.9 kg": "11–15,9 кг",
 "16–29.9 kg": "16–29,9 кг",
 "≥ 30 kg": "≥ 30 кг",
 "< 115 mm": "< 115 мм",
 "115 – < 125 mm": "115 – < 125 мм",
 "< −3 SD": "< −3 SD",
 "−3 to < −2 SD": "от −3 до < −2 SD",
 "50–100 mL ReSoMal": "50–100 мл ReSoMal",
 "Cal": "ккал",
 "MSF cholera §5.8.": "MSF, холера §5.8.",
 "WHO weight-for-length and weight-for-height: −3 SD and −2 SD cut-offs": "ВОЗ, вес к длине тела и вес к росту: пороги −3 SD и −2 SD",
 "Weight below the −3 SD value = severe wasting (SAM); from −3 SD to below −2 SD = moderate wasting. A child under 2 measured standing: add 0.7 cm; a child of 2 or older measured lying: subtract 0.7 cm. The calculator uses the same values at 0.5 cm steps.": "Вес ниже значения −3 SD = тяжёлое истощение (ТОН); от −3 SD до менее −2 SD = умеренное истощение. Ребёнок до 2 лет, измеренный стоя: прибавить 0,7 см; ребёнок 2 лет и старше, измеренный лёжа: вычесть 0,7 см. Калькулятор использует те же значения с шагом 0,5 см.",
 "Length (cm), lying, under 2 years": "Длина тела (см), лёжа, до 2 лет",
 "Height (cm), standing, 2–5 years": "Рост (см), стоя, 2–5 лет",
 "cm": "см",
 "Boys −3 SD": "Мальчики −3 SD",
 "Boys −2 SD": "Мальчики −2 SD",
 "Girls −3 SD": "Девочки −3 SD",
 "Girls −2 SD": "Девочки −2 SD"
};
